// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXhNS7S5Z2cGoUxDZP_F1QPsDfgEouLZk',
    appId: '1:1075941527672:web:390de838383821ebcb9d8d',
    messagingSenderId: '1075941527672',
    projectId: 'contact-app-d7910',
    authDomain: 'contact-app-d7910.firebaseapp.com',
    storageBucket: 'contact-app-d7910.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADCTuEwEe30Gufh2fdzi_jPM963sfhvRA',
    appId: '1:1075941527672:android:0f1038aeb1e06f9fcb9d8d',
    messagingSenderId: '1075941527672',
    projectId: 'contact-app-d7910',
    storageBucket: 'contact-app-d7910.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDaotRZzP8m31fCRgEv0NK0ar7eurE8II',
    appId: '1:1075941527672:ios:84eeac2b78cf8de5cb9d8d',
    messagingSenderId: '1075941527672',
    projectId: 'contact-app-d7910',
    storageBucket: 'contact-app-d7910.appspot.com',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDaotRZzP8m31fCRgEv0NK0ar7eurE8II',
    appId: '1:1075941527672:ios:c2b2d94fa23c7e54cb9d8d',
    messagingSenderId: '1075941527672',
    projectId: 'contact-app-d7910',
    storageBucket: 'contact-app-d7910.appspot.com',
    iosBundleId: 'com.example.contactsApp.RunnerTests',
  );
}
